[project]
name = "image-to-md-editor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.133.1",
    "google-cloud-vision>=3.12.1",
    "python-multipart>=0.0.22",
    "uvicorn[standard]>=0.41.0",
]
